hostname: reservoirs.localhost
mariadb:
  auth:
    rootPassword: root-password
    password: password
  persistence:
    enabled: false
web:
  repository:
    image: k3d-registry.localhost:5111/ijmacd/reservoirs
  ingress:
    enabled: true
  gateway:
    enabled: false
  tls:
    enabled: true
  local:
    enabled: true
