appVersion: ""
hostname: reservoirs.ijmacd.com
mariadb:
  auth:
    database: reservoirs
    username: reservoirs_user
  initdbScriptsConfigMap: reservoirs-mariadb-init
  primary:
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 102Mi
web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/reservoirs
    tag: ""
  existingSecret:
  ingress:
    enabled: false
  gateway:
    enabled: true
    parentRef:
      name: gateway
      namespace: default
      sectionName: https
  tls:
    enabled: false
  local:
    enabled: false
  resources:
    requests:
      memory: 21Mi
      cpu: 10m
    limits:
      memory: 21Mi
update:
  resources:
    requests:
      memory: 40Mi
      cpu: 5m
    limits:
      memory: 40Mi
