apiVersion: batch/v1
kind: CronJob
metadata:
  name: '{{ .Release.Name }}-update'
  labels:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    app.kubernetes.io/component: reservoirs-update
    app.kubernetes.io/part-of: reservoirs
spec:
  schedule: "30 15 * * *"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: reservoirs-update
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: reservoirs-update
              image: '{{ .Values.web.repository.image }}{{ if ne .Values.appVersion "" }}:{{ .Values.appVersion }}{{ end }}'
              command: ["node"]
              args: ["./update.js"]
              env:
                - name: DATABASE_HOST
                  value: {{ .Release.Name }}-mariadb
                - name: DATABASE_NAME
                  value: {{ .Values.mariadb.auth.database }}
                - name: DATABASE_USER
                  value: {{ .Values.mariadb.auth.username }}
                - name: DATABASE_PASS
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-mariadb
                      key: mariadb-password
              resources:
                requests:
                  memory: 50Mi
                  cpu: 50m
                limits:
                  memory: 100Mi
                  cpu: 100m